<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

The number 13 has the binary representation ``00001101``. Likewise,
16 is represented by ``00010000``.  The bit-wise OR of 13 and 16 is
then ``00011101``, or 29:


In [ ]:
np.bitwise_or(13, 16)

29

In [ ]:
np.binary_repr(29)

'11101'

In [ ]:
np.bitwise_or(32, 2)

34

In [ ]:
np.bitwise_or([33, 4], 1)

array([33,  5])

In [ ]:
np.bitwise_or([33, 4], [1, 2])

array([33,  6])

In [ ]:
np.bitwise_or(np.array([2, 5, 255]), np.array([4, 4, 4]))

array([  6,   5, 255])

In [ ]:
np.array([2, 5, 255]) | np.array([4, 4, 4])

array([  6,   5, 255])

In [ ]:
np.bitwise_or(np.array([2, 5, 255, 2147483647], dtype=np.int32),
              np.array([4, 4, 4, 2147483647], dtype=np.int32))

array([         6,          5,        255, 2147483647], dtype=int32)

In [ ]:
np.bitwise_or([True, True], [False, True])

array([ True,  True])

The ``|`` operator can be used as a shorthand for ``np.bitwise_or`` on
ndarrays.


In [ ]:
x1 = np.array([2, 5, 255])
x2 = np.array([4, 4, 4])
x1 | x2

array([  6,   5, 255])