<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [ ]:
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [ ]:
x[np.nonzero(x)]

array([3, 4, 5, 6])

In [ ]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

A common use for ``nonzero`` is to find the indices of an array, where
a condition is True.  Given an array `a`, the condition `a` > 3 is a
boolean array and since False is interpreted as 0, np.nonzero(a > 3)
yields the indices of the `a` where the condition is true.


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

Using this result to index `a` is equivalent to using the mask directly:


In [ ]:
a[np.nonzero(a > 3)]

array([4, 5, 6, 7, 8, 9])

In [ ]:
a[a > 3]  # prefer this spelling

array([4, 5, 6, 7, 8, 9])

``nonzero`` can also be called as a method of the array.


In [ ]:
(a > 3).nonzero()

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))