<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.equal([0, 1, 3], np.arange(3))

array([ True,  True, False])

What is compared are values, not types. So an int (1) and an array of
length one can evaluate as True:


In [ ]:
np.equal(1, np.ones(1))

array([ True])

The ``==`` operator can be used as a shorthand for ``np.equal`` on
ndarrays.


In [ ]:
a = np.array([2, 4, 6])
b = np.array([2, 4, 2])
a == b

array([ True,  True, False])