<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.argmax(a)

5

In [ ]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [ ]:
np.argmax(a, axis=1)

array([2, 2])

Indexes of the maximal elements of a N-dimensional array:


In [ ]:
a.flat[np.argmax(a)]

15

In [ ]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
ind

(1, 2)

In [ ]:
a[ind]

15

In [ ]:
b = np.arange(6)
b[1] = 5
b

array([0, 5, 2, 3, 4, 5])

In [ ]:
np.argmax(b)  # Only the first occurrence is returned.

1

In [ ]:
x = np.array([[4,2,3], [1,0,3]])
index_array = np.argmax(x, axis=-1)
# Same as np.amax(x, axis=-1, keepdims=True)
np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1)

array([[4],
       [3]])

In [ ]:
# Same as np.amax(x, axis=-1)
np.take_along_axis(x, np.expand_dims(index_array, axis=-1),
    axis=-1).squeeze(axis=-1)

array([4, 3])

Setting `keepdims` to `True`,


In [ ]:
x = np.arange(24).reshape((2, 3, 4))
res = np.argmax(x, axis=1, keepdims=True)
res.shape

(2, 1, 4)