<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial.hermite_e import hermeint
hermeint([1, 2, 3]) # integrate once, value 0 at 0.

array([1., 1., 1., 1.])

In [ ]:
hermeint([1, 2, 3], m=2) # integrate twice, value & deriv 0 at 0

array([-0.25      ,  1.        ,  0.5       ,  0.33333333,  0.25      ]) # may vary

In [ ]:
hermeint([1, 2, 3], k=1) # integrate once, value 1 at 0.

array([2., 1., 1., 1.])

In [ ]:
hermeint([1, 2, 3], lbnd=-1) # integrate once, value 0 at -1

array([-1.,  1.,  1.,  1.])

In [ ]:
hermeint([1, 2, 3], m=2, k=[1, 2], lbnd=-1)

array([ 1.83333333,  0.        ,  0.5       ,  0.33333333,  0.25      ]) # may vary