<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Upcasting:


In [ ]:
np.array([1, 2, 3.0])

array([ 1.,  2.,  3.])

More than one dimension:


In [ ]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

Minimum dimensions 2:


In [ ]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

Type provided:


In [ ]:
np.array([1, 2, 3], dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

Data-type consisting of more than one element:


In [ ]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3], dtype=int32)

Creating an array from sub-classes:


In [ ]:
np.array(np.asmatrix('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [ ]:
np.array(np.asmatrix('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

Limiting the maximum dimensions with ``ndmax``:


In [ ]:
a = np.array([[1, 2], [3, 4]], dtype=object, ndmax=2)
a

array([[1, 2],
       [3, 4]], dtype=object)

In [ ]:
a.shape

(2, 2)

In [ ]:
b = np.array([[1, 2], [3, 4]], dtype=object, ndmax=1)
b

array([list([1, 2]), list([3, 4])], dtype=object)

In [ ]:
b.shape

(2,)