<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial import legendre as L
c = (1,2,3)
L.legint(c)

array([ 0.33333333,  0.4       ,  0.66666667,  0.6       ]) # may vary

In [ ]:
L.legint(c, 3)

array([  1.66666667e-02,  -1.78571429e-02,   4.76190476e-02, # may vary
         -1.73472348e-18,   1.90476190e-02,   9.52380952e-03])

In [ ]:
L.legint(c, k=3)

 array([ 3.33333333,  0.4       ,  0.66666667,  0.6       ]) # may vary

In [ ]:
L.legint(c, lbnd=-2)

array([ 7.33333333,  0.4       ,  0.66666667,  0.6       ]) # may vary

In [ ]:
L.legint(c, scl=2)

array([ 0.66666667,  0.8       ,  1.33333333,  1.2       ]) # may vary