<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

In [ ]:
np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

In [ ]:
np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

Use the `order` keyword to specify a field to use when sorting a
structured array:


In [ ]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
np.sort(a, order='height')                        # doctest: +SKIP

array([('Galahad', 1.7, 38), ('Arthur', 1.8, 41),
       ('Lancelot', 1.8999999999999999, 38)],
      dtype=[('name', '|S10'), ('height', '<f8'), ('age', '<i4')])

Sort by age, then height if ages are equal:


In [ ]:
np.sort(a, order=['age', 'height'])               # doctest: +SKIP

array([('Galahad', 1.7, 38), ('Lancelot', 1.8999999999999999, 38),
       ('Arthur', 1.8, 41)],
      dtype=[('name', '|S10'), ('height', '<f8'), ('age', '<i4')])