<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Vector cross-product.


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.linalg.cross(x, y)

array([-3,  6, -3])

Multiple vector cross-products. Note that the direction of the cross
product vector is defined by the *right-hand rule*.


In [ ]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.linalg.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([[4, 5], [6, 1], [2, 3]])
np.linalg.cross(x, y, axis=0)

array([[-24,  6],
       [ 18, 24],
       [-6,  -18]])