<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

These are the indices that would allow you to access the upper triangular
part of any 3x3 array:


In [ ]:
iu = np.mask_indices(3, np.triu)

For example, if `a` is a 3x3 array:


In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[iu]

array([0, 1, 2, 4, 5, 8])

An offset can be passed also to the masking function.  This gets us the
indices starting on the first diagonal right of the main one:


In [ ]:
iu1 = np.mask_indices(3, np.triu, 1)

with which we now extract only three elements:


In [ ]:
a[iu1]

array([1, 2, 5])