<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
np.random.seed(123)
import numpy.matlib
np.matlib.randn(1)

matrix([[-1.0856306]])

In [ ]:
np.matlib.randn(1, 2, 3)

matrix([[ 0.99734545,  0.2829785 , -1.50629471],
        [-0.57860025,  1.65143654, -2.42667924]])

Two-by-four matrix of samples from the normal distribution with
mean 3 and standard deviation 2.5:


In [ ]:
2.5 * np.matlib.randn((2, 4)) + 3

matrix([[1.92771843, 6.16484065, 0.83314899, 1.30278462],
        [2.76322758, 6.72847407, 1.40274501, 1.8900451 ]])