<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
freqs = np.fft.fftfreq(10, 0.1)
freqs

array([ 0.,  1.,  2., ..., -3., -2., -1.])

In [ ]:
np.fft.fftshift(freqs)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

Shift the zero-frequency component only along the second axis:


In [ ]:
freqs = np.fft.fftfreq(9, d=1./9).reshape(3, 3)
freqs

array([[ 0.,  1.,  2.],
       [ 3.,  4., -4.],
       [-3., -2., -1.]])

In [ ]:
np.fft.fftshift(freqs, axes=(1,))

array([[ 2.,  0.,  1.],
       [-4.,  3.,  4.],
       [-1., -3., -2.]])