<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, -2j], [2j, 5]])
LA.eigvalsh(a)

array([ 0.17157288,  5.82842712]) # may vary

In [ ]:
# demonstrate the treatment of the imaginary part of the diagonal
a = np.array([[5+2j, 9-2j], [0+2j, 2-1j]])
a

array([[5.+2.j, 9.-2.j],
       [0.+2.j, 2.-1.j]])

In [ ]:
# with UPLO='L' this is numerically equivalent to using LA.eigvals()
# with:
b = np.array([[5.+0.j, 0.-2.j], [0.+2.j, 2.-0.j]])
b

array([[5.+0.j, 0.-2.j],
       [0.+2.j, 2.+0.j]])

In [ ]:
wa = LA.eigvalsh(a)
wb = LA.eigvals(b)
wa

array([1., 6.])

In [ ]:
wb

array([6.+0.j, 1.+0.j])