<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

A 2-dimensional array of size 2 x 3, composed of 4-byte integer
elements:


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)

<class 'numpy.ndarray'>

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int32')

The array can be indexed using Python container-like syntax:


In [ ]:
# The element of x in the *second* row, *third* column, namely, 6.
x[1, 2]

   6

For example :ref:`slicing <arrays.indexing>` can produce views of
the array:


In [ ]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [ ]:
y[0] = 9 # this also changes the corresponding element in x
y

array([9, 5], dtype=int32)

In [ ]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)