<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

To take the running sum of four successive values:


In [ ]:
import numpy as np
np.add.reduceat(np.arange(8),[0,4, 1,5, 2,6, 3,7])[::2]

array([ 6, 10, 14, 18])

A 2-D example:


In [ ]:
x = np.linspace(0, 15, 16).reshape(4,4)
x

array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])

```

# reduce such that the result has the following five rows:
# [row1 + row2 + row3]
# [row4]
# [row2]
# [row3]
# [row1 + row2 + row3 + row4]

```

In [ ]:
np.add.reduceat(x, [0, 3, 1, 2, 0])

array([[12.,  15.,  18.,  21.],
       [12.,  13.,  14.,  15.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [24.,  28.,  32.,  36.]])

```

# reduce such that result has the following two columns:
# [col1 * col2 * col3, col4]

```

In [ ]:
np.multiply.reduceat(x, [0, 3], 1)

array([[   0.,     3.],
       [ 120.,     7.],
       [ 720.,    11.],
       [2184.,    15.]])