<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, ..., 7, 8, 9])

When `axis` is specified, `values` must have the correct shape.


In [ ]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)

Traceback (most recent call last):
    ...
ValueError: all the input arrays must have same number of dimensions, but
the array at index 0 has 2 dimension(s) and the array at index 1 has 1
dimension(s)

In [ ]:
a = np.array([1, 2], dtype=np.int_)
c = np.append(a, [])
c

array([1., 2.])

In [ ]:
c.dtype

float64

Default dtype for empty ndarrays is `float64` thus making the output of dtype
`float64` when appended with dtype `int64`