<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
signal = np.array([1, 2, 3, 4, 3, 2])
np.fft.fft(signal)

array([15.+0.j,  -4.+0.j,   0.+0.j,  -1.-0.j,   0.+0.j,  -4.+0.j]) # may vary

In [ ]:
np.fft.hfft(signal[:4]) # Input first half of signal

array([15.,  -4.,   0.,  -1.,   0.,  -4.])

In [ ]:
np.fft.hfft(signal, 6)  # Input entire signal and truncate

array([15.,  -4.,   0.,  -1.,   0.,  -4.])

In [ ]:
signal = np.array([[1, 1.j], [-1.j, 2]])
np.conj(signal.T) - signal   # check Hermitian symmetry

array([[ 0.-0.j,  -0.+0.j], # may vary
       [ 0.+0.j,  0.-0.j]])

In [ ]:
freq_spectrum = np.fft.hfft(signal)
freq_spectrum

array([[ 1.,  1.],
       [ 2., -2.]])