<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.histogram([1, 2, 1], bins=[0, 1, 2, 3])

(array([0, 2, 1]), array([0, 1, 2, 3]))

In [ ]:
np.histogram(np.arange(4), bins=np.arange(5), density=True)

(array([0.25, 0.25, 0.25, 0.25]), array([0, 1, 2, 3, 4]))

In [ ]:
np.histogram([[1, 2, 1], [1, 0, 1]], bins=[0,1,2,3])

(array([1, 4, 1]), array([0, 1, 2, 3]))

In [ ]:
a = np.arange(5)
hist, bin_edges = np.histogram(a, density=True)
hist

array([0.5, 0. , 0.5, 0. , 0. , 0.5, 0. , 0.5, 0. , 0.5])

In [ ]:
hist.sum()

2.4999999999999996

In [ ]:
np.sum(hist * np.diff(bin_edges))

1.0

Automated Bin Selection Methods example, using 2 peak random data
with 2000 points.

.. code-block:: python

    import matplotlib.pyplot as plt
    import numpy as np

    rng = np.random.RandomState(10)  # deterministic random data
    a = np.hstack((rng.normal(size=1000),
                   rng.normal(loc=5, scale=2, size=1000)))
    plt.hist(a, bins='auto')  # arguments are passed to np.histogram
    plt.title("Histogram with 'auto' bins")
    plt.show()
