<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Sort names: first by surname, then by name.


In [ ]:
import numpy as np
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0])

In [ ]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

Sort according to two numerical keys, first by elements
of ``a``, then breaking ties according to elements of ``b``:


In [ ]:
a = [1, 5, 1, 4, 3, 4, 4]  # First sequence
b = [9, 4, 0, 4, 0, 2, 1]  # Second sequence
ind = np.lexsort((b, a))  # Sort by `a`, then by `b`
ind

array([2, 0, 4, 6, 5, 3, 1])

In [ ]:
[(a[i], b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

Compare against `argsort`, which would sort each key independently.


In [ ]:
np.argsort((b, a), kind='stable')

array([[2, 4, 6, 5, 1, 3, 0],
       [0, 2, 4, 3, 5, 6, 1]])

To sort lexicographically with `argsort`, we would need to provide a
structured array.


In [ ]:
x = np.array([(ai, bi) for ai, bi in zip(a, b)],
             dtype = np.dtype([('x', int), ('y', int)]))
np.argsort(x)  # or np.argsort(x, order=('x', 'y'))

array([2, 0, 4, 6, 5, 3, 1])

The zeroth axis of `keys` always corresponds with the sequence of keys,
so 2D arrays are treated just like other sequences of keys.


In [ ]:
arr = np.asarray([b, a])
ind2 = np.lexsort(arr)
np.testing.assert_equal(ind2, ind)

Accordingly, the `axis` parameter refers to an axis of *each* key, not of
the `keys` argument itself. For instance, the array ``arr`` is treated as
a sequence of two 1-D keys, so specifying ``axis=0`` is equivalent to
using the default axis, ``axis=-1``.


In [ ]:
np.testing.assert_equal(np.lexsort(arr, axis=0),
                        np.lexsort(arr, axis=-1))

For higher-dimensional arrays, the axis parameter begins to matter. The
resulting array has the same shape as each key, and the values are what
we would expect if `lexsort` were performed on corresponding slices
of the keys independently. For instance,


In [ ]:
x = [[1, 2, 3, 4],
     [4, 3, 2, 1],
     [2, 1, 4, 3]]
y = [[2, 2, 1, 1],
     [1, 2, 1, 2],
     [1, 1, 2, 1]]
np.lexsort((x, y), axis=1)

array([[2, 3, 0, 1],
       [2, 0, 3, 1],
       [1, 0, 3, 2]])

Each row of the result is what we would expect if we were to perform
`lexsort` on the corresponding row of the keys:


In [ ]:
for i in range(3):
    print(np.lexsort((x[i], y[i])))

[2 3 0 1]
[2 0 3 1]
[1 0 3 2]